### ISSUE TITLE
Mismatch in entity annotation

### ISSUE THREAD

**Issue by rykovan** [jakelever/pgxmine#2]
When I run `run_example.sh` I'm getting the following error:

```bash
$ ./prepareData.sh
$ ./run_example.sh
+ rm -f example/aligned.bioc.xml example/sentences.bioc.xml example/kb.tsv example/mini_unfiltered.tsv example/mini_collated.tsv example/mini_sentences.tsv
+ python align.py --inBioc example/input.bioc.xml --annotations /dev/fd/63 --outBioc example/aligned.bioc.xml
++ zcat data/bioconcepts2pubtatorcentral.gz
2022-09-28 14:18:27 0 26736037
Done!
+ python findPGxSentences.py --inBioc example/aligned.bioc.xml --filterTermsFile pgx_filter_terms.txt --outBioc example/sentences.bioc.xml
Traceback (most recent call last):
  File "findPGxSentences.py", line 65, in <module>
    for corpus in kindred.iterLoad('biocxml',args.inBioc):
  File "/home/natalia/git/kindred/kindred/loadFunctions.py", line 387, in iterLoad
    kindredDocs = convertBiocDocToKindredDocs(document)
  File "/home/natalia/git/kindred/kindred/loadFunctions.py", line 311, in convertBiocDocToKindredDocs
    assert entityText == a.text, "Mismatch in entity annotation between expected text (%s) and extracted text (%s) using offset info for passage with text: %s" % (a.text, entityText, text)
AssertionError: Mismatch in entity annotation between expected text (methamphetamine) and extracted text (hetamine use as) using offset info for passage with text: Although stimulant dependence is highly heritable, few studies have examined genetic influences on methamphetamine dependence. We performed a candidate gene study of 52 SNPs and pretreatment methamphetamine use frequency among 263 methamphetamine dependent Hispanic and Non-Hispanic White participants of several methamphetamine outpatient clinical trials in Los Angeles. One SNP, rs7591784 was significantly associated with pretreatment methamphetamine use frequency following Bonferroni correction (p < 0.001) in males but not females. We then examined rs7591784 and methamphetamine urine drug screen results during 12 weeks of outpatient treatment among males with treatment outcome data available (N = 94) and found rs7591784 was significantly associated with methamphetamine use during treatment controlling for pretreatment methamphetamine use. rs7591784 is near CREB1 and in a linkage disequilibrium block with rs2952768, previously shown to influence CREB1 expression. The CREB signaling pathway is involved in gene expression changes related to chronic use of multiple drugs of abuse including methamphetamine and these results suggest that variability in CREB signaling may influence pretreatment frequency of methamphetamine use as well as outcomes of outpatient treatment. Medications targeting the CREB pathway, including phosphodiesterase inhibitors, warrant investigation as pharmacotherapies for methamphetamine use disorders.
```

Am I missing something?

**Comment by rykovan** [comment]
Apparently [align.py](https://github.com/jakelever/pgxmine/blob/master/align.py) outputs annotation's offsets relative to passage's text:

```xml
<passage>
    <infon key="section">abstract</infon>
    <offset>185</offset>
    <text>Although stimulant dependence is highly heritable, few studies have examined genetic influences on methamphetamine dependence. We performed a candidate gene study of 52 SNPs and pretreatment methamphetamine use frequency among 263 methamphetamine dependent Hispanic and Non-Hispanic White participants of several methamphetamine outpatient clinical trials in Los Angeles. One SNP, rs7591784 was significantly associated with pretreatment methamphetamine use frequency following Bonferroni correction (p &lt; 0.001) in males but not females. We then examined rs7591784 and methamphetamine urine drug screen results during 12 weeks of outpatient treatment among males with treatment outcome data available (N = 94) and found rs7591784 was significantly associated with methamphetamine use during treatment controlling for pretreatment methamphetamine use. rs7591784 is near CREB1 and in a linkage disequilibrium block with rs2952768, previously shown to influence CREB1 expression. The CREB signaling pathway is involved in gene expression changes related to chronic use of multiple drugs of abuse including methamphetamine and these results suggest that variability in CREB signaling may influence pretreatment frequency of methamphetamine use as well as outcomes of outpatient treatment. Medications targeting the CREB pathway, including phosphodiesterase inhibitors, warrant investigation as pharmacotherapies for methamphetamine use disorders.</text>
        <annotation id="T16">
            <infon key="type">Chemical</infon>
            <infon key="conceptid">MESH:D008694</infon>
            <location offset="99" length="15" />
            <text>methamphetamine</text>
        </annotation>
...
```

```python
>>> text = "Although stimulant dependence is highly heritable, few studies have examined genetic influences on methamphetamine dependence."
>>> text[99:99+15]
'methamphetamine'
```

But [convertBiocDocToKindredDocs](https://github.com/jakelever/kindred/blob/298d4868d9c9babf82d44de1bba2a9874145ce5a/kindred/loadFunctions.py#L276) takes into account passage's offset (which is [185](https://github.com/jakelever/pgxmine/blob/9467f6a7d3457c2ebf2a4559b9aed684fc320504/example/input.bioc.xml#L24) in the current case) and thus fails. @jakelever please let me know if you do agree with my conclusion and what would be the best way to fix the issue.

**Comment by jakelever** [comment]
I've updated the run_example script which now takes a pre-aligned file in the input file. The PubTator align code has moved over to the [BioText](https://github.com/jakelever/biotext) project.
